-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.315.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2016/7/15 15:28:35
-- Server version: 5.7.12
-- Client version: 4.1

CREATE TABLE m_activity (
  activity_id int(8) NOT NULL AUTO_INCREMENT COMMENT '活动ID',
  activity_name varchar(255) NOT NULL DEFAULT '' COMMENT '活动名称',
  activity_type tinyint(4) NOT NULL DEFAULT 0 COMMENT '活动类型',
  channel_id tinyint(4) NOT NULL DEFAULT 0 COMMENT '渠道',
  province_id int(11) NOT NULL DEFAULT 0 COMMENT '省份',
  start_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '开始时间',
  end_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '结束时间',
  put_amount bigint(20) NOT NULL DEFAULT 0 COMMENT '投入总金额',
  PRIMARY KEY (activity_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '营销活动表'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_pay_flow (
  flow_id bigint(20) NOT NULL DEFAULT 0 COMMENT '收银台交易流水',
  biz_id bigint(20) NOT NULL DEFAULT 0 COMMENT '业务订单流水',
  biz_type tinyint(4) NOT NULL DEFAULT 0 COMMENT '业务类型',
  thd_flow_id varchar(50) DEFAULT '' COMMENT '第三方交易流水',
  pay_type tinyint(4) DEFAULT 0 COMMENT '支付类型 1-微信 2-支付宝 3-招行',
  notify_url varchar(255) DEFAULT '' COMMENT '通知地址',
  return_url varchar(255) DEFAULT '' COMMENT '回调地址',
  total_amount int(11) NOT NULL DEFAULT 0 COMMENT '总交易金额',
  pay_amount int(11) NOT NULL DEFAULT 0 COMMENT '实际支付金额',
  create_time datetime NOT NULL,
  pay_time datetime DEFAULT NULL,
  state tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态(0:失效,1:生效)',
  pay_state tinyint(4) DEFAULT 0 COMMENT '支付状态 0-未支付 2-支付成功，业务待处理 3-支付成功，业务处理失败 1-支付成功且业务处理成功 4-已退款 8-支付失败',
  fail_code varchar(100) DEFAULT '' COMMENT '支付失败编码',
  fail_desc varchar(255) DEFAULT '' COMMENT '支付失败描述',
  refund_id bigint(20) DEFAULT 0 COMMENT '退款单号',
  refund_reason varchar(255) DEFAULT '' COMMENT '退款原因',
  thd_refund_id varchar(50) DEFAULT '' COMMENT '第三方退款单号',
  refund_time datetime DEFAULT NULL COMMENT '退款时间',
  PRIMARY KEY (flow_id),
  INDEX IDX_pay_flow_biz_id (biz_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_policy (
  policy_id int(10) NOT NULL AUTO_INCREMENT COMMENT '策略id',
  activity_id int(8) NOT NULL DEFAULT 0 COMMENT '活动id',
  policy_name varchar(1024) NOT NULL DEFAULT '' COMMENT '策略名称，前台展示用 eg:限上海，限上午',
  policy_type tinyint(4) DEFAULT 1 COMMENT '策略类型 1-代金券 2-红包 3-补贴',
  policy_priority tinyint(2) DEFAULT 1 COMMENT '优先级 越大优先级越高1-99',
  effect_days int(4) DEFAULT 0 COMMENT '有效时长天数',
  PRIMARY KEY (policy_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '策略是将规则打包，关联给活动
例：一个活动，要发1，3，5块的代金券，5块的要求订单金额满30才能用，那么1'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_put_rule (
  rule_id int(10) NOT NULL AUTO_INCREMENT COMMENT '规则id',
  policy_id int(10) NOT NULL DEFAULT 0 COMMENT '策略id',
  face_value int(4) NOT NULL DEFAULT 0 COMMENT '面值',
  total_amount int(10) NOT NULL DEFAULT 0 COMMENT '总数量',
  initial_amount int(10) NOT NULL DEFAULT 0 COMMENT '最初生成状态数量',
  received_amount int(10) NOT NULL DEFAULT 0 COMMENT '已领取状态数量',
  used_amount int(10) NOT NULL DEFAULT 0 COMMENT '已使用状态数量',
  expired_amount int(10) DEFAULT 0 COMMENT '已失效状态数量',
  PRIMARY KEY (rule_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '投放规则表'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_quota (
  quota_id int(8) NOT NULL COMMENT '指标id',
  quota_name varchar(50) NOT NULL DEFAULT '' COMMENT '指标名称',
  field_name varchar(50) NOT NULL DEFAULT '' COMMENT '对应字段',
  state tinyint(1) NOT NULL DEFAULT 1 COMMENT '状态 0-废弃 1-在用',
  PRIMARY KEY (quota_id)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2340
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '指标配置表'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_receive_rule (
  rule_id int(10) NOT NULL AUTO_INCREMENT COMMENT '规则id',
  policy_id int(10) NOT NULL DEFAULT 0 COMMENT '策略id',
  quota_id int(8) DEFAULT 0 COMMENT '指标id',
  quota_field varchar(50) NOT NULL DEFAULT '' COMMENT '指标字段',
  operator varchar(5) NOT NULL DEFAULT '' COMMENT '操作符',
  quota_value varchar(8) NOT NULL DEFAULT '' COMMENT '指标值',
  PRIMARY KEY (rule_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '领取规则表'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_use_rule (
  rule_id int(10) NOT NULL AUTO_INCREMENT COMMENT '规则id',
  policy_id int(10) NOT NULL DEFAULT 0 COMMENT '策略id',
  quota_id int(8) DEFAULT 0 COMMENT '指标id',
  quota_filed varchar(50) NOT NULL DEFAULT '' COMMENT '指标字段',
  operator varchar(5) NOT NULL DEFAULT '' COMMENT '操作符',
  quota_value varchar(8) NOT NULL DEFAULT '' COMMENT '指标值',
  PRIMARY KEY (rule_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '使用规则表'
ROW_FORMAT = DYNAMIC;

CREATE TABLE m_voucher (
  voucher_id bigint(20) NOT NULL COMMENT '券id',
  policy_id int(8) NOT NULL DEFAULT 0 COMMENT '策略id',
  user_id bigint(20) DEFAULT 0 COMMENT '用户id',
  face_value int(4) NOT NULL DEFAULT 0 COMMENT '面额',
  effect_time datetime DEFAULT '0000-00-00 00:00:00' COMMENT '生效时间',
  expire_time datetime DEFAULT '0000-00-00 00:00:00' COMMENT '失效时间',
  receive_time datetime DEFAULT '0000-00-00 00:00:00' COMMENT '领取时间',
  use_time datetime DEFAULT '0000-00-00 00:00:00' COMMENT '使用时间',
  state tinyint(2) NOT NULL DEFAULT 3 COMMENT '状态 0-已失效 1-已领取 2-已使用 3-已生成',
  PRIMARY KEY (voucher_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = '代金券表'
ROW_FORMAT = DYNAMIC;